[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sdl2 = "0.35.2"
getset = "0.1.2"
itertools = "0.10.3"

[lib]
name = "ui"
path = "ui/src/lib.rs"
