[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sdl2 = "0.34"
getset = "0.1.1"
itertools = "0.10.1"

[lib]
name = "ui"
path = "ui/src/lib.rs"